DSP-1064 Create metadata endpoint in JS-LIB
dasch-swiss/dsp-js-lib pull request #258
Opened 2020-11-12 16:01 UTC by mpro7

resolves DSP-1064

2020-11-12 16:39 UTC, tobiasschweizer commented on src/api/v2/metadata/metadata-endpoint-v2.ts
> +        return this.httpGet("");
in `models/v2/metadata` you could add a class like this:

```ts
@JsonObject("ProjectMetadata")
export class ProjectMetadata {

    @JsonProperty("http://ns.dasch.swiss/repository#hasName", String)
    name: string = "";

    @JsonProperty("http://ns.dasch.swiss/repository#hasKeywords", [String])
    keywords: string[] = [];

    -> add more properties, check https://www.npmjs.com/package/json2typescript for more info
}
```

And then in the endpoint:

```ts
    declare let require: any; // http://stackoverflow.com/questions/34730010/angular2-5-minute-install-bug-require-is-not-defined
const jsonld = require("jsonld/dist/jsonld.js");

    ...

    getMetadata(projectIri: string): Observable< ProjectMetadata > {

        return this.httpGet("/" + encodeURIComponent(projectIri)).pipe(
            // expand all Iris
            mergeMap((ajaxResponse: AjaxResponse) => {
                return jsonld.compact(ajaxResponse.response, {});
            }),
            map((jsonldobj: object) => {
                // create an instance of ProjectMetadata from JSON-LD
                return this.jsonConvert.deserializeObject(jsonldobj, ProjectMetadata);
            })
        );
    }
```

For the put operation, you would have to use json2typescript's `serializeObject` method for the payload and make a class for the response.

2020-11-12 16:41 UTC, tobiasschweizer commented on src/api/v2/metadata/metadata-endpoint-v2.ts
> +        return this.httpGet("");
For error handling, you can add the `catchError` operator to the pipe like in the other endpoints, the return then also includes a `ApiResponseError`.

2020-11-30 09:37 UTC, tobiasschweizer requested changes
Please see my comment. If you have questions, just ping me.

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/custom-converters/date-converter.ts
> +export class DateConverter implements JsonCustomConvert<Date> { // or just string?
If you are suing the JS date class, you have to be aware of timezone issues / parsing problems (see creation date in the following example):

![Screenshot 2020-11-30 at 10 32 49](https://user-images.githubusercontent.com/6000023/100592493-75d2eb00-32f7-11eb-899b-b386461323ff.png)


Also you have to take into account that months are 0 based (0-11), see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date. But maybe since you are creating a date from a string, this is not an issue.

However, when the client is providing a `Date` using params, this could be an issue.

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/custom-converters/date-converter.ts
> +            "@value": dateObject
How would the string representation of a `Date` instance look in JSON then?

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/custom-converters/person-organization-converter.ts
> +export class PersonOrganizationConverter implements JsonCustomConvert<Person | Organization | object> {
Is `object` needed?

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/custom-converters/person-organization-converter.ts
> +    deserialize(obj: object): Person | Organization | object {
Is `object` needed?

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/custom-converters/person-organization-converter.ts
> +        const orgProp = Constants.dspRepoBase + "hasName";
I think you could also make constants for "hasName" etc.

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/custom-converters/person-organization-converter.ts
> +        if (obj.hasOwnProperty(orgProp) || obj.hasOwnProperty(personProp)) {
What else could this be than a `Person` or `Organization`?

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/custom-converters/url-to-object-converter.ts
> +export class UrlToObjectConverter implements JsonCustomConvert<object> {
What is this converter used for? Could it use a class name instead of simply `object`?

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/custom-converters/url-to-string-converter.ts
> +            return val[Constants.urlTypeLowerCase];
Why lowercase?

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/project-metadata/attribution-definition.ts
> +    @JsonProperty(Constants.agent, IdConverter) //convert to Person base on @id
That would be the next step, right?

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/project-metadata/place-definition.ts
> +    place: object = {};
Could this be made more specific than `object`?

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/project-metadata/project-definition.ts
> +    discipline: object = {};
Could this be made more specific than `object`?

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/project-metadata/project-metadata.ts
> +    projectsMetadata: any[] = [];
Could this be made more specific than `any`?

2020-11-30 09:37 UTC, tobiasschweizer commented on src/models/v2/project-metadata/update-project-metadata.ts
> +    @JsonProperty("http://api.knora.org/ontology/knora-api/v2#result", String)
Isn't there a constant for this?

2020-11-30 09:37 UTC, tobiasschweizer commented on test-framework/package.json
> +    "e2e-local": "yalc add @dasch-swiss/dsp-js && npm install && npm run webdriver-update && npm run e2e",
nice!

2020-11-30 09:37 UTC, tobiasschweizer commented on test-framework/src/app/app.component.ts
> +import { ProjectsMetadata } from '@dasch-swiss/dsp-js/src/models/v2/project-metadata/project-metadata';
I think once you have added `ProjectsMetadata` to index (see comment above), this should be `import { ProjectsMetadata } from '@dasch-swiss`.

2020-11-30 09:37 UTC, tobiasschweizer commented on test-framework/e2e/src/app.e2e-spec.ts
> +  it('it should update a project metadata', () => {
Nice!

2020-11-30 10:08 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +     * @param knoraApiConfig
These params come from the extended class `Endpoint`, even there they are not documented ;). Moreover, they are neither documented in any of existing endpoint classes, which extend the above one. So following it I should remove contructor documentation.

2020-11-30 10:10 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +        return this.httpGet(`/${encodeURIComponent(resourceIri)}`).pipe(
Indeed. IMO it is nice feature and looks more readable for me.

2020-11-30 10:11 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +    convertProjectsList = (projectsJsonLd: object, jsonConvert: JsonConvert): ProjectsMetadata => {
Correct, but does it make sense for only one method?

2020-11-30 11:04 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +            if (Object.keys(projectsJsonLd).length > 0) {
It shouldn't be, but this is what I'm checking here. There is still no validation on the backend...

2020-11-30 11:05 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +     * Updates a project metadata from Knora.
![image](https://user-images.githubusercontent.com/29251288/100602550-50001300-3304-11eb-8b77-e4bdea3c0c9d.png)
You are repeating yourself 😃

2020-11-30 11:10 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +    updateProjectMetadata(resourceIri: string, metadata: any): Observable<UpdateProjectMetadataResponse | ApiResponseError> {
Well, the type doesn't exist.

2020-11-30 11:13 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +     * @param knoraApiConfig
Ok you caught me, I will improve this in https://github.com/dasch-swiss/dsp-js-lib/pull/264

2020-11-30 11:13 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +        return this.httpGet(`/${encodeURIComponent(resourceIri)}`).pipe(
I think it makes sense for actual templates (multiline strings).

2020-11-30 11:14 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +    convertProjectsList = (projectsJsonLd: object, jsonConvert: JsonConvert): ProjectsMetadata => {
Maybe there will be more utility methods at some point. If you want to leave it here, make it private.

2020-11-30 11:16 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +     * Updates a project metadata from Knora.
I prefer the notion "to be consistent" ;-)

2020-11-30 11:16 UTC, mpro7 commented on src/models/v2/Constants.ts
> +    static urlTypeLowerCase = Constants.urlType.toLocaleLowerCase();
One is used as type, the other as value and it is dictated by schema, see example below:
```
          "http://ns.dasch.swiss/repository#hasURL": {
            "@type": "https://schema.org/URL",
            "https://schema.org/url": "https://snf.ch"
          },
```

2020-11-30 11:17 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +    updateProjectMetadata(resourceIri: string, metadata: any): Observable<UpdateProjectMetadataResponse | ApiResponseError> {
It should be `ProjectsMetadata`. So you are passing in an instance of a class that is then going to be serialized. Like in the example of creating a user.

2020-11-30 11:18 UTC, tobiasschweizer commented on src/models/v2/Constants.ts
> +    static urlTypeLowerCase = Constants.urlType.toLocaleLowerCase();
Ok, I understand. Could you just give them clearer names?

2020-11-30 11:20 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +            if (Object.keys(projectsJsonLd).length > 0) {
So this is a case that should never occur? Maybe throwing an error would be appropriate?

2020-11-30 11:32 UTC, mpro7 commented on src/models/v2/custom-converters/url-to-string-converter.ts
> +            return val[Constants.urlTypeLowerCase];
[Explained here](https://github.com/dasch-swiss/dsp-js-lib/pull/258#discussion_r532521320)

2020-11-30 11:32 UTC, mpro7 commented on src/models/v2/project-metadata/attribution-definition.ts
> +    @JsonProperty(Constants.agent, IdConverter) //convert to Person base on @id
Correct.

2020-11-30 11:33 UTC, tobiasschweizer commented on src/models/v2/custom-converters/url-to-string-converter.ts
> +            return val[Constants.urlTypeLowerCase];
got it :-)

2020-11-30 11:35 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +     * Reads a project metadata from Knora.
Fixed with b13483e.

2020-11-30 11:35 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +            // creates the same structure for single object incoming from API
Fixed with b13483e.

2020-11-30 11:36 UTC, mpro7 commented on src/index.ts
> +
Fixed with b13483e.

2020-11-30 11:37 UTC, mpro7 commented on src/models/v2/Constants.ts
> +import { constants } from "buffer";
Some intellisense mistake. Fixed with b13483e.

2020-11-30 11:37 UTC, mpro7 commented on src/models/v2/Constants.ts
> +    static dsp = "http://ns.dasch.swiss/"
Fixed with b13483e.

2020-11-30 11:37 UTC, mpro7 commented on src/models/v2/Constants.ts
> +    static propID = "https://schema.org/propertyID";
Fixed with b13483e.

2020-11-30 11:38 UTC, mpro7 commented on src/models/v2/project-metadata/project-metadata.ts
> +    projectsMetadata: any[] = [];
Fixed with b13483e.

2020-11-30 11:38 UTC, mpro7 commented on src/models/v2/project-metadata/update-project-metadata.ts
> +    @JsonProperty("http://api.knora.org/ontology/knora-api/v2#result", String)
Fixed with b13483e.

2020-11-30 11:38 UTC, mpro7 commented on test-framework/src/app/app.component.ts
> +import { ProjectsMetadata } from '@dasch-swiss/dsp-js/src/models/v2/project-metadata/project-metadata';
Fixed with b13483e.

2020-11-30 13:51 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +     * @param knoraApiConfig
So I remove it now and will update it in the second go.

2020-11-30 14:09 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +     * @param knoraApiConfig
I think you can leave it as it is now.

2020-11-30 14:12 UTC, tobiasschweizer commented on src/index.ts
> +export { ProjectsMetadata } from "./models/v2/project-metadata/project-metadata";
It is desirable to have both, `ProjectsMetadata` and `Dataset`, exported.

2020-11-30 14:13 UTC, tobiasschweizer commented on src/models/v2/Constants.ts
> +    static propID = "https://schema.org/propertyID";
great, thx.

2020-11-30 14:16 UTC, tobiasschweizer commented on src/models/v2/project-metadata/update-project-metadata.ts
> +    @JsonProperty("http://api.knora.org/ontology/knora-api/v2#result", String)
I think you could even use `Constants.Result`. I tried to avoid having strings in the mappers at all.

2020-11-30 14:16 UTC, tobiasschweizer commented on test-framework/src/app/app.component.ts
> +import { ProjectsMetadata } from '@dasch-swiss/dsp-js/src/models/v2/project-metadata/project-metadata';
great

2020-11-30 14:27 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +        return this.httpPut(`/${encodeURIComponent(resourceIri)}`, metadata).pipe(
After applying your suggestion I keep getting 500 Error - need to investigate it.

2020-11-30 14:29 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +        return this.httpPut(`/${encodeURIComponent(resourceIri)}`, metadata).pipe(
maybe there is something going wrong in the serialization of the class. Have you ever tested this before?

2020-11-30 14:35 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +        return this.httpGet(`/${encodeURIComponent(resourceIri)}`).pipe(
Ok I replaced this in 8953d37 with concatenation to keep it consistent.

2020-11-30 14:35 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +    convertProjectsList = (projectsJsonLd: object, jsonConvert: JsonConvert): ProjectsMetadata => {
Made it private in 8953d37.

2020-11-30 14:35 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +            if (Object.keys(projectsJsonLd).length > 0) {
Good question. Was thinking to throw an error anyway, but in this case I just commented it (8953d37) and verify in the next go, because there is a lack of information how does this will work.

2020-11-30 14:36 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +    updateProjectMetadata(resourceIri: string, metadata: any): Observable<UpdateProjectMetadataResponse | ApiResponseError> {
Obvious thing, thanks. Fixed in 8953d37.

2020-11-30 14:36 UTC, mpro7 commented on src/models/v2/Constants.ts
> +    static urlTypeLowerCase = Constants.urlType.toLocaleLowerCase();
Sure. Done in 8953d37.

2020-11-30 14:38 UTC, mpro7 commented on src/models/v2/custom-converters/date-converter.ts
> +            "@value": dateObject
Here are few examples:

      "http://ns.dasch.swiss/repository#hasDateCreated": {
        "@type": "http://www.w3.org/2001/XMLSchema#date",
        "@value": "2001-09-26"
      },
      "http://ns.dasch.swiss/repository#hasDateModified": {
        "@type": "http://www.w3.org/2001/XMLSchema#date",
        "@value": "2020-04-26"
      },
      "http://ns.dasch.swiss/repository#hasDatePublished": {
        "@type": "http://www.w3.org/2001/XMLSchema#date",
        "@value": "2002-09-24"
      },

2020-11-30 14:38 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +        return this.httpPut(`/${encodeURIComponent(resourceIri)}`, metadata).pipe(
The idea is that the user instantiates the class `metadata = new ProjectsMetadata()`, then sets the values of the instance, which then gets converted with `this.jsonConvert.serialize(metadata)` before sending it to the API. 

This then throws an error if there is a problem.

2020-11-30 14:40 UTC, mpro7 commented on src/models/v2/custom-converters/date-converter.ts
> +export class DateConverter implements JsonCustomConvert<Date> { // or just string?
Hmm, so maybe to keep it simple as I actually get the date as a string, should I keep string instead of date?

2020-11-30 14:41 UTC, tobiasschweizer commented on src/models/v2/custom-converters/date-converter.ts
> +            "@value": dateObject
ah, so this is really 2001. I though this was wrong.

2020-11-30 14:41 UTC, tobiasschweizer commented on src/models/v2/custom-converters/date-converter.ts
> +export class DateConverter implements JsonCustomConvert<Date> { // or just string?
maybe I got it wrong, I though 2001 was a bug.

2020-11-30 14:42 UTC, tobiasschweizer commented on src/models/v2/custom-converters/date-converter.ts
> +export class DateConverter implements JsonCustomConvert<Date> { // or just string?
However, it would be desirable to handle this consistently throughout the lib. So there could be an extra task for this.

2020-11-30 14:43 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +    convertProjectsList = (projectsJsonLd: object, jsonConvert: JsonConvert): ProjectsMetadata => {
ok, great

2020-11-30 14:43 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +        return this.httpGet(`/${encodeURIComponent(resourceIri)}`).pipe(
ok, thx.

2020-11-30 14:44 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +            if (Object.keys(projectsJsonLd).length > 0) {
ok

2020-11-30 14:49 UTC, mpro7 commented on src/models/v2/custom-converters/person-organization-converter.ts
> +export class PersonOrganizationConverter implements JsonCustomConvert<Person | Organization | object> {
Yes, because sometimes this needs to deal with simple object structure (references), see example:

        "http://ns.dasch.swiss/repository#hasFunder": {
          "@id": "http://ns.dasch.swiss/test-funder"
        },

In this case it has no sense to keep all types, because `Person` and `Organization` are redundant. However I could maybe create simple type/interface for references, but does it make sense?

2020-11-30 14:50 UTC, mpro7 commented on src/models/v2/custom-converters/person-organization-converter.ts
> +    deserialize(obj: object): Person | Organization | object {
Same as [above](https://github.com/dasch-swiss/dsp-js-lib/pull/258#discussion_r532446595).

2020-11-30 14:51 UTC, mpro7 commented on src/models/v2/custom-converters/person-organization-converter.ts
> +        if (obj.hasOwnProperty(orgProp) || obj.hasOwnProperty(personProp)) {
Same as [above](https://github.com/dasch-swiss/dsp-js-lib/pull/258#discussion_r532446595).

2020-11-30 14:55 UTC, mpro7 commented on src/models/v2/project-metadata/place-definition.ts
> +    place: object = {};
Do you mean by this, should I create class/interface for every object used or it is ok to use primitive type?

2020-11-30 15:24 UTC, mpro7 commented on src/models/v2/custom-converters/date-converter.ts
> +export class DateConverter implements JsonCustomConvert<Date> { // or just string?
No, 2001 is how they set it, but you are right about timezones. What I actually get is just pure date in string like `"2001-09-26"`and no information about timezone, hours etc. So I could set hours to 0 using `setHours(0,0,0,0)`. But to keep it consistent I should maybe use pure string instead here. This, as you mentioned, could be improved to `Date` type in the future in a separate task (I think it makes sense to create JS-LIB refactor epic and this kind of tasks there).

2020-11-30 17:08 UTC, mpro7 commented on src/models/v2/custom-converters/person-organization-converter.ts
> +export class PersonOrganizationConverter implements JsonCustomConvert<Person | Organization | object> {
Fixed in f61c3b5.

2020-11-30 17:09 UTC, mpro7 commented on src/models/v2/custom-converters/date-converter.ts
> +export class DateConverter implements JsonCustomConvert<Date> { // or just string?
Changed to return string instead of date type in f61c3b5.

2020-12-01 13:07 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +        return this.httpPut(`/${encodeURIComponent(resourceIri)}`, metadata).pipe(
Partially covered by de6cbdb, rest will be done in new task DSP-1126.

2020-12-01 13:08 UTC, mpro7 commented on src/models/v2/custom-converters/person-organization-converter.ts
> +        const orgProp = Constants.dspRepoBase + "hasName";
Done in de6cbdb.

2020-12-01 13:08 UTC, mpro7 commented on src/models/v2/custom-converters/url-to-object-converter.ts
> +export class UrlToObjectConverter implements JsonCustomConvert<object> {
Will cover it in DSP-1126.

2020-12-01 13:09 UTC, mpro7 commented on src/models/v2/project-metadata/place-definition.ts
> +    place: object = {};
Will be covered in new task DSP-1126.

2020-12-01 13:11 UTC, mpro7 commented on src/models/v2/project-metadata/project-definition.ts
> +    discipline: object = {};
Will be done in new task DSP-1126.

2020-12-01 13:11 UTC, mpro7 commented on src/index.ts
> +export { ProjectsMetadata } from "./models/v2/project-metadata/project-metadata";
Done in de6cbdb.

2020-12-01 13:37 UTC, tobiasschweizer approved these changes
Ok, see my last remarks.

2020-12-01 13:37 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +        return this.httpPut(`/${encodeURIComponent(resourceIri)}`, metadata).pipe(
Ok!

2020-12-01 13:37 UTC, tobiasschweizer commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +            // if (Object.keys(projectsJsonLd).length > 0) {
Will you deal with `if (Object.keys(projectsJsonLd).length > 0)` in DSP-1126?

2020-12-01 13:37 UTC, tobiasschweizer commented on src/models/v2/custom-converters/distribution-converter.ts
> +    serialize(val: IDistribution): object {
I suggest to base the converters for URL and distribution on a common base structure.

`type IDistribution = IUrl;` is semantically confusion whereas it makes sense structurally.
Could you do that in DSP-1126?

2020-12-01 13:37 UTC, tobiasschweizer commented on src/models/v2/custom-converters/url-to-object-converter.ts
> +export class UrlToObjectConverter implements JsonCustomConvert<object> {
Ok.

2020-12-01 13:37 UTC, tobiasschweizer commented on src/models/v2/project-metadata/place-definition.ts
> +    place: object = {};
Ok.

2020-12-01 13:37 UTC, tobiasschweizer commented on src/models/v2/project-metadata/project-definition.ts
> +    discipline: object = {};
Ok.

2020-12-01 13:37 UTC, tobiasschweizer commented on test-framework/tsconfig.json
> +    "resolveJsonModule": true,
Once https://dasch.myjetbrains.com/youtrack/issue/DSP-1126 is done, this can be removed as well as `metadat-payload.json`, right?

2020-12-01 13:39 UTC, mpro7 commented on src/api/v2/project-metadata/metadata-endpoint-v2.ts
> +            // if (Object.keys(projectsJsonLd).length > 0) {
That's the plan.

2020-12-01 13:42 UTC, mpro7 commented on src/models/v2/custom-converters/distribution-converter.ts
> +    serialize(val: IDistribution): object {
Will cover it there too. Was going to ask you if having interface here is ok, or should we relay only on classes? Whatever you answer, I will probably use one for both cases. And yes, I've decided to implement the base for converters also in next task.

2020-12-01 13:42 UTC, mpro7 commented on test-framework/tsconfig.json
> +    "resolveJsonModule": true,
Correct.

2020-12-01 14:14 UTC, merged