Improved Docs
dasch-swiss/dsp-js-lib pull request #264
Opened 2020-11-25 13:20 UTC by tobiasschweizer

resolves DSP-1050

2020-12-02 07:30 UTC, kilchenmann commented on contribution.md
> +
It would be good to have a link to our general contribution guidelines here. Something like:

"Want to contribute? Please read our [general contribution guidelines](https://docs.dasch.swiss/developers/dsp/contribution/) first."

I am pretty sure you will find better words 😉

2020-12-02 07:30 UTC, kilchenmann commented on contribution.md
> +1. `npm run prepare-dev-publication`: prepares a dev version of the library **before** building it. The dev version contains code to create mocked data to be used in unit test of projects using DSP-J
Could you mention that this command will modify `index.ts`, `package.json` and `tsconfig.json`. It should be run only once and **it must not be committed**.

2020-12-02 07:30 UTC, kilchenmann commented on contribution.md
> +1. `npm run prepare-dev-publication`: prepares a dev version of the library **before** building it. The dev version contains code to create mocked data to be used in unit test of projects using DSP-J
Ah I just see that you have already mentioned this on line 72

2020-12-02 09:07 UTC, tobiasschweizer commented on contribution.md
> +
done in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/a5c85712e0bc06476217eaf4e59afa11499aa669

A question regarding the contribution guidelines: Are these made solely for members of the DaSCH that have writing access to our GitHub repos? What about external developers? Would they have to fork the repo to submit a PR?

2020-12-02 09:10 UTC, tobiasschweizer commented on contribution.md
> +1. `npm run prepare-dev-publication`: prepares a dev version of the library **before** building it. The dev version contains code to create mocked data to be used in unit test of projects using DSP-J
I improved the message in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/8cff541b9090b80e980df3a1fd1fe87bf4000ba0

2020-12-02 09:15 UTC, mpro7 requested changes

2020-12-02 09:15 UTC, mpro7 commented on design-documentation.md
>  It communicates directly with the Knoa API, taking care of deserializing JSON responses received from Knora.
`Knora API` should be replaced by `DSP-API`. I see here is the typo: **Knoa API** - so replace tool failed to change it ;), but also in lines 29 and 34 and many more in this file you use Knora instead - should all this be changed to DSP-API?

2020-12-02 09:15 UTC, mpro7 commented on design-documentation.md
> +DSP-API v2 is used to create, read, search, and modify data (resources and values).
Use `,` or `and`,

2020-12-02 09:15 UTC, mpro7 commented on test-framework/README.md
> +Follow the instructions given in section "Build and Publish a Local Version" of `contribution.md`.
Link?

2020-12-02 09:15 UTC, mpro7 commented on test-framework/README.md
> +see section "Build and Integrate DSP-JS-LIB".
Link?

2020-12-02 09:29 UTC, mpro7 commented
Also not sure if this is anywhere mentioned, to run e2e tests in test-framework, DSP-API **needs to be restarted every time before** with volume deletion. Is this correct?

2020-12-02 09:30 UTC, tobiasschweizer commented on README.md
> +DSP-JS-LIB depends on [RxJS](https://rxjs.dev/guide/overview) and is web framework agnostic (it can be used with Angular, React, Vue.js etc.).
RxJS is a peer dependency of DPS-JS-LIB. This means that when DPS-JS-LIB is used within an npm project and `npm install` is executed, it is **not** installed automatically.

The reason for this is that RxJS's `Observable` is used in DPS-JS-LIB's public API. If the "host project" and DPS-JS-LIB have different versions of RxJS, then the `Observable` returned by DPS-JS-LIB is not the same thing as the `Observable` used in your "host project" which causes compilation errors.

So the peer dependency ensures that the "host project" installs a compatible version of RxJS (major version 6).
Npm would complain if the "host project" installs an incompatible version.
This is an information relevant to all users of  DPS-JS-LIB, also when you do not develop it actively.

I found these sources very helpful:
- https://indepth.dev/posts/1193/create-your-standalone-angular-library-in-10-minutes
- https://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins#34645112

2020-12-02 09:32 UTC, tobiasschweizer commented on README.md
> +See `contribution.md`.
Good idea.

@kilchenmann Could this be done as a step of the build process when moving them to docs.dasch.swiss?
Or could we actually link the source file on GitHub?

2020-12-02 09:33 UTC, tobiasschweizer commented on contribution.md
> +See `design-documentation.md`.
see my [comment](https://github.com/dasch-swiss/dsp-js-lib/pull/264#discussion_r533968549)

2020-12-02 09:34 UTC, tobiasschweizer commented on test-framework/README.md
> +Follow the instructions given in section "Build and Publish a Local Version" of `contribution.md`.
see my [comment](https://github.com/dasch-swiss/dsp-js-lib/pull/264#discussion_r533968549)

2020-12-02 09:34 UTC, tobiasschweizer commented on test-framework/README.md
> +see section "Build and Integrate DSP-JS-LIB".
see my [comment](https://github.com/dasch-swiss/dsp-js-lib/pull/264#discussion_r533968549)

2020-12-02 09:38 UTC, tobiasschweizer commented on README.md
> +See `contribution.md`.
in any case, this file will be shown on npmjs.com. So whatever we do, it also needs to make sense there.

2020-12-02 09:40 UTC, tobiasschweizer commented on README.md
> +- **system**: DSP-API's health status
I would like to link to the API docs: "Consult the API docs for more details.". But I think we really need to decide how the docs are built and published on each release.

2020-12-02 09:45 UTC, mpro7 commented on README.md
> +DSP-JS-LIB depends on [RxJS](https://rxjs.dev/guide/overview) and is web framework agnostic (it can be used with Angular, React, Vue.js etc.).
I think you didn't get my point. Usually in readme files you can see dependencies list. Seeing word `depends` here I would think about all external dependencies and seeing only RxJS, I would think here is the only one dependency, but in fact there are more (e.g. json2typscript), which are listed in contribution file. This just confused me.

2020-12-02 09:47 UTC, mpro7 commented on README.md
> +- **system**: DSP-API's health status
So maybe it is enough to mention: See the detailed description in `design-documentation.md` file?

2020-12-02 09:55 UTC, tobiasschweizer commented on README.md
> +DSP-JS-LIB depends on [RxJS](https://rxjs.dev/guide/overview) and is web framework agnostic (it can be used with Angular, React, Vue.js etc.).
I understand. I can mention the other two dependencies as well to make it consistent.

2020-12-02 10:03 UTC, kilchenmann commented on README.md
> +See `contribution.md`.
At the moment you could set the link to the file in github repo:
<https://github.com/dasch-swiss/dsp-js-lib/blob/main/contribution.md>

same with design-documentation:
<https://github.com/dasch-swiss/dsp-js-lib/blob/main/design-documentation.md>

2020-12-02 10:03 UTC, tobiasschweizer commented on README.md
> +DSP-JS-LIB depends on [RxJS](https://rxjs.dev/guide/overview) and is web framework agnostic (it can be used with Angular, React, Vue.js etc.).
done in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/bde6ec5400045409fc703b83d745b6934bf2e1df

2020-12-02 10:04 UTC, tobiasschweizer commented on contribution.md
> +This library depends on `RxJS`, `jsonld`, and `json2typescript`.
done in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/bde6ec5400045409fc703b83d745b6934bf2e1df

2020-12-02 10:05 UTC, tobiasschweizer commented on README.md
> +- **system**: DSP-API's health status
My rationale was that an app developer that is not interested in developing DSP-JS-LIB but only his own app would find a link to the API docs (built with typedoc).

2020-12-02 10:06 UTC, kilchenmann commented on design-documentation.md
> +DSP-API v2 is used to create, read, search, and modify data (resources and values).
@mpro7 It's an "Oxford comma".

2020-12-02 10:08 UTC, tobiasschweizer commented on contribution.md
> +This library works with `RxJS`'s major version defined in `package.json` . See `rxjs.md` for details.
good catch, fixed in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/5de46d4539fdf38f383962262bb6d9935e5a77cb

2020-12-02 10:09 UTC, tobiasschweizer commented on contribution.md
> +1. See if the tests pass on GitHub CI
fixed in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/0f89bc307abb075acd3483b510a6ef65139befa5

2020-12-02 10:09 UTC, kilchenmann commented on test-framework/README.md
> +Follow the instructions given in section "Build and Publish a Local Version" of `contribution.md`.
Could be done as:
<https://github.com/dasch-swiss/dsp-js-lib/blob/main/contribution.md#build-and-publish-a-local-version>

2020-12-02 10:14 UTC, tobiasschweizer commented on design-documentation.md
>  It communicates directly with the Knoa API, taking care of deserializing JSON responses received from Knora.
absolutely, done in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/83a3c1f46d0dd8f8146f55103b155a4225da799d

2020-12-02 10:17 UTC, tobiasschweizer commented on README.md
> +See `contribution.md`.
What about versions? If you release the npm package, then these links will always point to the latest version in `main` which could be different from the release.

2020-12-02 10:18 UTC, tobiasschweizer commented on contribution.md
> +Alternatively, you can run `npm run build-local` which combines the script mentioned above.
Is there some more explanation needed in `contribution.md`?

2020-12-02 10:20 UTC, tobiasschweizer commented on contribution.md
> +   - run `npm run webdriver-update` and then `npm run e2e`
I have seen this but I think here it is important to explain each step.

Maybe the script could be mentioned in `./test-framework/README.md`?

2020-12-02 10:20 UTC, tobiasschweizer commented on test-framework/README.md
> +Follow the instructions given in section "Build and Publish a Local Version" of `contribution.md`.
see my [comment](https://github.com/dasch-swiss/dsp-js-lib/pull/264#discussion_r534051170)

2020-12-02 10:23 UTC, tobiasschweizer commented
> Also not sure if this is anywhere mentioned, to run e2e tests in test-framework, DSP-API **needs to be restarted every time before** with volume deletion. Is this correct?

In `test-framework/README.md`, I added the sentence:

> Make sure that DSP-API's database is in its initial state. Reload the data if necessary.

I think the details how to do this should be covered by the DSP-API docs. I usually delete all the volumes. I believe there is a problem with stopping the db container.

2020-12-02 10:31 UTC, subotic commented on contribution.md
> +
Yes, they would need to fork the repo and then open a PR. We still have problems running the tests on PRs coming from the outside (not sure if on all or on some repositories), so for technical reasons, it is currently probably not possible to contribute from the outside of the organization.

2020-12-02 10:32 UTC, kilchenmann commented on README.md
> +See `contribution.md`.
Yes this is a general problem. This will be solved as soon dsp-docs is improved. There we'll have the versioning implemented. The main problem will be: How can we update the corresponding version number in the README. I just had a look at @angular/material on npmjs. They support only one link in the package's README to the main documentation without versioning. It redirects always to the latest documentation even when you select an other version.

2020-12-02 10:37 UTC, kilchenmann commented on README.md
> +See `contribution.md`.
It's be better to have a link to a documentation file, even if it redirects to the latest version, than just mention a file and the user has to find the correctly versioned file by himself.

2020-12-02 10:41 UTC, tobiasschweizer commented on README.md
> +See `contribution.md`.
> It's be better to have a link to a documentation file, even if it redirects to the latest version, than just mention a file and the user has to find the correctly versioned file by himself.

I disagree. Inappropriate documentation is worse than no documentation. Imagine that in the latest version there is a usage information that does not apply to the older release the user is working with. That will be a source of confusion and frustration: the user will think think he is doing something wrong.

2020-12-02 10:42 UTC, tobiasschweizer commented on README.md
> +See `contribution.md`.
maybe we could use the GitHub permalinks, but I am not sure how hard it would be to manage them.

2020-12-02 10:48 UTC, kilchenmann commented on README.md
> +See `contribution.md`.
But then you have to update the linked version in the README before releasing?

It can be tricky and as you said "hard to manage".

2020-12-02 10:52 UTC, mpro7 requested changes
So what are we doing with links? Is it better to link at all or do not link to do not mess up with versions? I would link - [here is why](https://github.com/dasch-swiss/dsp-js-lib/pull/264#r533968549).

2020-12-02 10:52 UTC, mpro7 commented on README.md
> +- **system**: DSP-API's health status
IMO, since you've split the readme to few files, would be actually more informative to add mention in main README, to show this is extended there. But I leave the decision to you.

2020-12-02 10:52 UTC, mpro7 commented on README.md
> +See `contribution.md`.
That was my point of every comment suggesting the link. Linking makes life way easier. One just can click to open in external tab and keep read the docs.

2020-12-02 10:52 UTC, mpro7 commented on contribution.md
> +Alternatively, you can run `npm run build-local` which combines the script mentioned above.
Looking at my notes, you've mentioned something about `rm -rf node_modules build dist`, but not sure now where this could be mentioned here.

2020-12-02 10:52 UTC, mpro7 commented on contribution.md
> +   - run `npm run webdriver-update` and then `npm run e2e`
Ok, it is already there.

2020-12-02 10:52 UTC, mpro7 commented on test-framework/README.md
> +Alternatively, run `npm run e2e-local` which combines the steps mentioned above.
Actually it does a little bit more than 2 above scripts:
`"e2e-local": "yalc add @dasch-swiss/dsp-js && npm install && npm run webdriver-update && npm run e2e"`

2020-12-02 10:55 UTC, mpro7 commented on README.md
> +See `contribution.md`.
Maybe just mention that link follows to the newest version - which helps to remember to look for the version one is checking?

2020-12-02 11:02 UTC, kilchenmann commented on README.md
> +See `contribution.md`.
The same thing happens to the badge at the top of the README. It displays always the latest version.

2020-12-02 13:10 UTC, tobiasschweizer commented on README.md
> +- **system**: DSP-API's health status
Ok, done in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/5c3918ab00be8ea0f0b73541adf57b52fd8c1d75.

2020-12-02 13:11 UTC, tobiasschweizer commented on contribution.md
> +Alternatively, you can run `npm run build-local` which combines the script mentioned above.
This is just for getting rid of all installed dependencies and start fresh. This works the same for all npm projects.

2020-12-02 13:16 UTC, tobiasschweizer commented on test-framework/README.md
> +Alternatively, run `npm run e2e-local` which combines the steps mentioned above.
clarified in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/f120a334a4af6baf8debd3f9ce4e025d05f48946

2020-12-02 13:18 UTC, tobiasschweizer commented
> So what are we doing with links? Is it better to link at all or do not link to do not mess up with versions? I would link - [here is why](https://github.com/dasch-swiss/dsp-js-lib/pull/264#r533968549).

Could we try to find a general solution for this? Other repos will need that too and it should be handled in a consistent manner so all fits together in the end. How about tomorrow after the meeting?

2020-12-02 13:33 UTC, mpro7 approved these changes
From my side it looks ok now. So we can move the links topic to other task.

2020-12-02 13:34 UTC, tobiasschweizer commented
> From my side it looks ok now. So we can move the links topic to another task, talking about it first, like suggested.

Shall I schedule a meeting for tomorrow?

2020-12-03 09:23 UTC, mdelez requested changes
Making our docs great again!

2020-12-03 09:23 UTC, mdelez commented on contribution.md
> +so the component under test can react to it.
"the component being tested can react to it"

2020-12-03 09:23 UTC, mdelez commented on contribution.md
> +Therefore, the mock has been made a stand-alone testing component called `MockOntology` that can be reused.
"Therefore, a stand-alone testing component has been made for this mock called `MockOntology` that can be reused."

2020-12-03 09:23 UTC, mdelez commented on contribution.md
> +Since `MockOntology` is complex, some global assertions are made to guarantee that the mock behaves as the actual component.
"behaves like the actual component"

2020-12-03 09:23 UTC, mdelez commented on design-documentation.md
> +An `Endpoint` offers methods to communicate with DSP-API. At the current state, two main groups of endpoints have been implemented:
"In its current state"

2020-12-03 09:23 UTC, mdelez commented on design-documentation.md
> +DSP-API System endpoints inform about DSP-API's status.
Not exactly sure what this is trying to say, perhaps "DSP-API System endpoints provide information about DSP-API's status."?

2020-12-03 09:23 UTC, mdelez commented on design-documentation.md
> +The `HealthEndpointSystem` returns DSP-API's health status including information about the is version.
"about the version"

2020-12-03 09:23 UTC, mdelez commented on design-documentation.md
>  `ResourcesConversionUtil.createReadResourceSequence` is a public method that takes JSON-LD representing zero, one or more resources and returns an array of `ReadResource`. For each resource serialize
"zero, one, or more" - the additional comma makes it easier to comprehend

the sentence at the end
"Each property value serialized as JSON-LD is converted to a `ReadValue` if a cardinality for it exists for the resource class at hand."

2020-12-03 09:23 UTC, mdelez commented on design-documentation.md
> +`GenericCache` is an abstract and generic class. The generic type is the type of object that is going to be cached, e.g., an `ReadOntology`. The key is the IRI of the object that is cached. `GenericC
"`GenericCache` ensures that a specific element is only requested once from DSP-API if several asynchronous for the same element are performed." - remove "also"

"but in a non-blocking way, i.e. the requested element is returned immediately when it is ready while the dependencies are still being resolved."

2020-12-03 09:23 UTC, mdelez commented on test-framework/README.md
> +From this directory, run the follwoing scripts:
following

2020-12-03 13:42 UTC, tobiasschweizer commented
after discussion with @kilchenmann and @mpro7: I will add links to the Markdown files and add a section in the README saying that these links always point to the latest version of the file, not necessarily the version / release the user is currently using.

2020-12-03 14:00 UTC, tobiasschweizer commented on README.md
> +Make sure that `rxjs` is installed in the required major version 6 with the framework you are using, e.g. Angular.
done in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/12cd1f1e32907dee89f63a7f4995602a55d4bc25

2020-12-03 14:00 UTC, tobiasschweizer commented on README.md
> +Consult the API docs for more details about the available endpoints..
done in 12cd1f1

2020-12-03 14:00 UTC, tobiasschweizer commented on README.md
> +    // for some reason, the request failed
done in 12cd1f1

2020-12-03 14:31 UTC, tobiasschweizer commented on contribution.md
> +The purpose of this library is facilitating the use of [DSP-API (Knora)](https://www.knora.org) in web client development.
done in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/8a12b842e831b6822eca96bda4bd0405f404ae11

2020-12-03 14:31 UTC, tobiasschweizer commented on contribution.md
> +1. `npm run prepare-dev-publication`: prepares a dev version of the library **before** building it. The dev version contains code to create mocked data to be used in unit test of projects using DSP-J
done in 8a12b84

2020-12-03 14:31 UTC, tobiasschweizer commented on contribution.md
> +1. `npm run npm-pack`: Tests and builds the library and then and packs the `./build/` folder into an NPM tgz package. The package is moved into a `./dist/` folder.
done in 8a12b84

2020-12-03 14:31 UTC, tobiasschweizer commented on contribution.md
> +These mocks were originally developed for internal use, but can be used to get data for unit test in projects that use DSP-JS-LIB.
done in 8a12b84

2020-12-03 14:31 UTC, tobiasschweizer commented on contribution.md
> +All files that are contained in `scripts/v2-test-data-config.json` will be copied this library's tests data when running `npm run integrate-v2-test-data`.
done in 8a12b84

2020-12-03 14:31 UTC, tobiasschweizer commented on contribution.md
> +Therefore, the mock has been made a stand-alone testing component called `MockOntology` that can be reused.
done in 8a12b84

2020-12-03 14:32 UTC, tobiasschweizer commented on contribution.md
> +Since `MockOntology` is complex, some global assertions are made to guarantee that the mock behaves as the actual component.
done in 8a12b84

2020-12-03 14:42 UTC, tobiasschweizer commented on design-documentation.md
> +An `Endpoint` offers methods to communicate with DSP-API. At the current state, two main groups of endpoints have been implemented:
done in https://github.com/dasch-swiss/dsp-js-lib/pull/264/commits/cc70b8e66daf67d18ad9e2aa4a36f1318cc7fa51

2020-12-03 14:42 UTC, tobiasschweizer commented on design-documentation.md
> +DSP-API System endpoints inform about DSP-API's status.
done in cc70b8e

2020-12-03 14:43 UTC, tobiasschweizer commented on design-documentation.md
> +The `HealthEndpointSystem` returns DSP-API's health status including information about the is version.
done in cc70b8e

2020-12-03 14:43 UTC, tobiasschweizer commented on design-documentation.md
>  `ResourcesConversionUtil.createReadResourceSequence` is a public method that takes JSON-LD representing zero, one or more resources and returns an array of `ReadResource`. For each resource serialize
done in cc70b8e

2020-12-03 14:43 UTC, tobiasschweizer commented on design-documentation.md
> +`GenericCache` is an abstract and generic class. The generic type is the type of object that is going to be cached, e.g., an `ReadOntology`. The key is the IRI of the object that is cached. `GenericC
done in cc70b8e

2020-12-03 14:43 UTC, tobiasschweizer commented on test-framework/README.md
> +From this directory, run the follwoing scripts:
done in cc70b8e

2020-12-03 14:53 UTC, tobiasschweizer commented
GitHub docs suggest to use relative links: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-readmes#relative-links-and-image-paths-in-readme-files

however, I am not sure how this looks on npm

2020-12-03 14:59 UTC, tobiasschweizer commented
I checked https://www.npmjs.com/package/rxjs and I figured that relative links are rewritten so they point to the location on GitHub.

2020-12-03 15:19 UTC, tobiasschweizer commented
@mpro7 I added the @category tag to the metadata endpoint. Once the whole implementation of the metadata endpoint is done, we should categorise all classes correctly. I did not do it yet because this would create merge conflicts.

2020-12-03 15:34 UTC, mdelez approved these changes
Very nice :)

2020-12-03 16:24 UTC, mpro7 approved these changes

2020-12-03 16:26 UTC, merged