Add Convenience Methods to Ontology Information
dasch-swiss/dsp-js-lib pull request #265
Opened 2020-12-03 06:42 UTC by tobiasschweizer

resolves DSP-442

2020-12-04 09:20 UTC, tobiasschweizer commented
@flavens I am already preparing a PR for the advanced search: https://github.com/dasch-swiss/dsp-ui-lib/pull/239

2020-12-04 11:10 UTC, tobiasschweizer commented
I will add some more tests on Monday.

2020-12-07 09:38 UTC, tobiasschweizer commented
Ok, I added the tests. The PR is now ready for review.

2020-12-07 10:35 UTC, mdelez requested changes

2020-12-07 10:35 UTC, mdelez commented on src/api/v2/ontology/ontologies-endpoint.spec.ts
> +                    expect(classDefs.length).toEqual(9);
Do you think there is a way to avoid a hardcoded number for all of the `length` assertions? If the test data changes, this could break so I'm thinking we could maybe make this more flexible.

2020-12-07 11:10 UTC, tobiasschweizer commented on src/api/v2/ontology/ontologies-endpoint.spec.ts
> +                    expect(classDefs.length).toEqual(9);
That's a good point. However, I think unit tests should have static expectations. The more flexible assertions get, the more complexity grows. I once have written some testing helper method that was quite flexible and I only found out later that it never worked correctly. So the test would not have caught errors correctly.

Nevertheless, I think your point is valid. There is an ongoing discussion about how not to generate (static) test data from Knora anymore, but to manage it inside this lib. This would be possible once there is a formal spec that test data can be validated against. So then we would only care about the formal correctness of the test data, and this wouldn't change unless there is a change in the format spec.

Now, the ontology JSON-LD is actually generated from a test ontology in Knora. If this ontology changes, then the assertions would be wrong and would have to be updated.

2020-12-07 14:04 UTC, mdelez approved these changes

2020-12-07 14:57 UTC, flavens approved these changes

2020-12-07 17:01 UTC, merged