DSP-1126 Finish metadata endpoint in JS-LIB
dasch-swiss/dsp-js-lib pull request #268
Opened 2020-12-07 09:34 UTC by mpro7

resolves DSP-1126

2020-12-10 07:48 UTC, tobiasschweizer commented
@mpro7 Is this PR ready for review?

2020-12-10 08:00 UTC, mpro7 commented
> @mpro7 Is this PR ready for review?

Sorry, not yet. I'm going to implement mapping I've showed you yesterday in right place, now ti is on test-framework, for easier debugging + I'll try to add some tests.

2020-12-10 14:27 UTC, tobiasschweizer commented
@mpro7 Would you mind applying the `@category` tag to the new files that you made for metadata?

For the model classes that you made, it would be:

https://github.com/dasch-swiss/dsp-js-lib/blob/82110f15ffc60d7346f92809497e49834a82dc7a/src/models/v2/resources/read/read-resource.ts#L12-L14

2020-12-14 10:10 UTC, tobiasschweizer requested changes
Could you check https://github.com/dasch-swiss/dsp-js-lib/pull/258/files/de6cbdbcba4c16707b1b2155a69f6b536883816c#diff-9a682acaad7adb19b18d7479b0f72f44896b792f949a1dc02011f734ac8d861e?

Please see my comments below.

2020-12-14 10:10 UTC, tobiasschweizer commented on src/models/v2/project-metadata/base-project-metadata.ts
> +export class BaseProjectMetadata extends BaseValue {
you should not inherit from `BaseValue` because this is not a value. Instead, you can make your own class with a type which you can inherit from.

2020-12-14 10:10 UTC, tobiasschweizer commented on src/models/v2/project-metadata/base-project-metadata.ts
> +        this.type = type;
Maybe you do not need to inherit from another class here.

Couldn't you just define `type` here and then from a class like `DataManagementPlan` the value for the type would be passed as an arg to the constructor.

2020-12-14 10:10 UTC, tobiasschweizer commented on src/models/v2/project-metadata/organization-definition.ts
> +    email?: string = undefined; //should the email be actually @id as in JSON-LD?
What about this todo?

2020-12-14 10:10 UTC, tobiasschweizer commented on src/models/v2/project-metadata/person-definition.ts
> +    email?: string = undefined; //should the email be actually @id as in JSON-LD?
What about this todo? :-)

2020-12-14 10:10 UTC, tobiasschweizer commented on src/models/v2/project-metadata/place-definition.ts
> +    place: IUrl = {} as IUrl;
Wouldn't this have to a be an instance of `Place` instead?

2020-12-14 10:56 UTC, mpro7 commented on src/models/v2/project-metadata/place-definition.ts
> +    place: IUrl = {} as IUrl;
No, because it creates endless loop, since we are inside `Place` class here. the URL interface deals with all urls like objects and this is why I've made all properties inside optional, just to be flexible.

2020-12-14 10:56 UTC, mpro7 commented on src/models/v2/project-metadata/person-definition.ts
> +    email?: string = undefined; //should the email be actually @id as in JSON-LD?
This is not TODO, rather the question to the metadata model, how the emails should be set.

2020-12-14 10:57 UTC, mpro7 commented on src/models/v2/project-metadata/organization-definition.ts
> +    email?: string = undefined; //should the email be actually @id as in JSON-LD?
Same as [here](https://github.com/dasch-swiss/dsp-js-lib/pull/268#discussion_r542293288).

2020-12-14 10:59 UTC, mpro7 commented on src/models/v2/project-metadata/base-project-metadata.ts
> +        this.type = type;
Well this is done by your suggestion. I could either have `type` in each class or do it like above, otherwise I was getting some errors.

2020-12-14 10:59 UTC, mpro7 commented on src/models/v2/project-metadata/base-funder-definition.ts
> +    email?: string = undefined; //should the email be actually @id as in JSON-LD?
Same as [here](https://github.com/dasch-swiss/dsp-js-lib/pull/268#discussion_r542293288).

2020-12-14 11:00 UTC, mpro7 commented on src/models/v2/custom-converters/url-to-url-object-converter.ts
> +export class UrlToUrlObjectConverter extends BaseUrlConverter {
Correct.

2020-12-14 11:00 UTC, mpro7 commented on src/models/v2/custom-converters/person-organization-converter.ts
> +                "@id": (obj as { [index: string]: string })["id"]
Correct.

2020-12-14 11:01 UTC, mpro7 commented on src/models/v2/custom-converters/person-organization-converter.ts
> +export class PersonOrganizationConverter implements JsonCustomConvert<Person | Organization | object> {
Too many possibilities here and [here](https://github.com/dasch-swiss/dsp-js-lib/pull/268#discussion_r542243145).

2020-12-14 11:02 UTC, mpro7 commented on src/models/v2/custom-converters/email-converter.ts
> +        const hasPrefix = email.hasOwnProperty("@id") && email["@id"].startsWith(Constants.Dsp);
It seems so, but this need to confirm with @BalduinLandolt .

2020-12-14 11:04 UTC, tobiasschweizer commented on src/models/v2/project-metadata/base-project-metadata.ts
> +        this.type = type;
I know that I suggested this :-) What I meant was to do a structurally equivalent thing, not inheriting from `BaseValue` which make no sense here.

2020-12-14 11:20 UTC, mpro7 commented on src/models/v2/custom-converters/email-converter.ts
> +            "@id": Constants.Dsp + email
Depends on [this one](https://github.com/dasch-swiss/dsp-js-lib/pull/268#discussion_r542296958).

2020-12-14 11:20 UTC, mpro7 commented on src/models/v2/custom-converters/distribution-converter.ts
> +            const obj = {} as IUrl;
Don't get this one.

2020-12-14 11:22 UTC, mpro7 commented on src/models/v2/custom-converters/base-url-converter.ts
> +        return val;
Correct.

2020-12-14 11:25 UTC, mpro7 commented on src/models/v2/custom-converters/base-url-converter.ts
> +    type?: string;
There is not. Base is to be extended by other URL object types, but not the advanced one.

2020-12-14 11:26 UTC, mpro7 commented on src/models/v2/custom-converters/advanced-url-object-converter.ts
> +            [Constants.SchemaUrlValue]: val.url
Depends on [that](https://github.com/dasch-swiss/dsp-js-lib/pull/268#discussion_r542231006).

2020-12-14 11:26 UTC, mpro7 commented on src/models/v2/custom-converters/advanced-url-object-converter.ts
> +                [Constants.SchemaPropID]: val.name
Depends on [that](https://github.com/dasch-swiss/dsp-js-lib/pull/268#discussion_r542231006).

2020-12-14 11:26 UTC, mpro7 commented on src/models/v2/Constants.ts
> +    static SchemaPostalAddress = Constants.SchemaBase + "/PostalAddress";
Thanks for the suggestion ;)

2020-12-14 11:28 UTC, mpro7 commented on src/index.ts
> +export { IUrl } from "./models/v2/custom-converters/base-url-converter";
I assign to this interface objects on the test-framework.

2020-12-14 11:35 UTC, mpro7 commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        for (const key in tempObj) {
Correct. It just goes deeper in the nested object structure to look for the key with value to be the same as `ref` argument. In short words, it takes person id value defined outside of the `Dataset` object and search for the reference id inside it, to replace with full `Person` instance.

2020-12-14 11:39 UTC, mpro7 commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +    const replaceReference = (obj: object, ref: string, replacer: any): Dataset => {
Although `obj` argument can be more specific, because it can be `Dataset` only, the `replacer` argument could be everything which will be outside of the Dataset model. In this iteration it is only `Person` type, but the other will come in next iteration I think.

2020-12-14 11:42 UTC, mpro7 commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        meta.projectsMetadata.push(datasetObj as Dataset);
ad. 1. Correct.
ad. 2. This is still not clear to me. There is no validation on the backend yet, so hard to check it. But currently on test-framework I place them outsitde.

2020-12-14 11:48 UTC, mpro7 commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        data.projectsMetadata.map(obj => {
I will have a look. I need to loop twice over the whole response `ProjectsMetadata` instance to find the `Dataset` instance at first, and at second to find and replace inside it all references found in another items of `ProjectsMetadata` list/array.

2020-12-14 11:58 UTC, tobiasschweizer commented on src/models/v2/custom-converters/distribution-converter.ts
> +            const obj = {} as IUrl;
every property of `IUrl` is optional, so `url.name`etc. could be `undefined`.

2020-12-14 12:12 UTC, BalduinLandolt commented on src/models/v2/custom-converters/email-converter.ts
> +        const hasPrefix = email.hasOwnProperty("@id") && email["@id"].startsWith(Constants.Dsp);
by prefix you mean `mailto:`? (I'm missing some context here) If so, I'm afraid not consistently.

2020-12-14 12:36 UTC, tobiasschweizer commented on src/models/v2/custom-converters/email-converter.ts
> +        const hasPrefix = email.hasOwnProperty("@id") && email["@id"].startsWith(Constants.Dsp);
I mean `Constants.dsp`, the metadata base path.

2020-12-14 15:49 UTC, mpro7 commented on src/models/v2/project-metadata/base-project-metadata.ts
> +        this.type = type;
Next time better set of advices please 😄 d92571c should satisfy you.

2020-12-14 15:51 UTC, mpro7 commented on src/models/v2/custom-converters/distribution-converter.ts
> +            const obj = {} as IUrl;
Probably not the best way to make it flexible type ;) I will try improve it.

2020-12-14 15:58 UTC, mpro7 commented on src/models/v2/custom-converters/email-converter.ts
> +        const hasPrefix = email.hasOwnProperty("@id") && email["@id"].startsWith(Constants.Dsp);
@BalduinLandolt All email values starts in our example with `http://ns.dasch.swiss/` and later on there is standart prefix@domain like benjamin.jones@test.ch. Is this by purpose or those are just the dummy data and the email format will be like usually eg. beaver@domain.com without any URL parts in it?

2020-12-14 16:25 UTC, mpro7 commented on src/models/v2/custom-converters/advanced-url-object-converter.ts
> +    deserialize(val: any): IUrl {
Explained [here](https://github.com/dasch-swiss/dsp-js-lib/pull/268#discussion_r542492544).

2020-12-14 16:27 UTC, mpro7 commented on src/models/v2/custom-converters/email-converter.ts
> +        const hasPrefix = email.hasOwnProperty("@id") && email["@id"].startsWith(Constants.Dsp);
@BalduinLandolt All email values start in our example with `http://ns.dasch.swiss/` and later on, there is standard prefix@domain like benjamin.jones@test.ch. Is this by purpose or those are just the dummy data and the email format will be like usually eg. beaver@domain.com without any URL parts in it?

2020-12-14 16:43 UTC, mpro7 commented on src/models/v2/custom-converters/person-organization-converter.ts
> +        if (obj.hasOwnProperty(Constants.DspHasName) || obj.hasOwnProperty(Constants.DspHasJobTitle)) {
Refactored in a2b915d.

2020-12-15 15:47 UTC, mpro7 commented on src/models/v2/custom-converters/distribution-converter.ts
> +            const obj = {} as IUrl;
Got confirmation that email property should be just a string, fixed in d7a5c32.

2020-12-15 15:48 UTC, mpro7 commented on src/models/v2/custom-converters/email-converter.ts
> +            "@id": Constants.Dsp + email
Email converter was removed in d7a5c32.

2020-12-15 15:49 UTC, mpro7 commented on src/models/v2/custom-converters/email-converter.ts
> +        const hasPrefix = email.hasOwnProperty("@id") && email["@id"].startsWith(Constants.Dsp);
fixed in d7a5c32.

2020-12-15 15:49 UTC, mpro7 commented on src/models/v2/project-metadata/person-definition.ts
> +    email?: string = undefined; //should the email be actually @id as in JSON-LD?
fixed in d7a5c32.

2020-12-15 15:50 UTC, mpro7 commented on src/models/v2/project-metadata/organization-definition.ts
> +    email?: string = undefined; //should the email be actually @id as in JSON-LD?
fixed in d7a5c32.

2020-12-15 15:50 UTC, mpro7 commented on src/models/v2/project-metadata/base-funder-definition.ts
> +    email?: string = undefined; //should the email be actually @id as in JSON-LD?
fixed in d7a5c32.

2020-12-15 16:38 UTC, mpro7 commented on src/models/v2/Constants.ts
> +    static SchemaPostalAddress = Constants.SchemaBase + "/PostalAddress";
Done in 
35f15cf

2020-12-15 18:12 UTC, mpro7 commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        data.projectsMetadata.map(obj => {
And adjusted it in a3748c4.

2020-12-15 18:13 UTC, mpro7 commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        meta.projectsMetadata.push(datasetObj as Dataset);
Adjusted in a3748c4.

2020-12-16 10:45 UTC, mpro7 commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        for (const key in tempObj) {
This has been fixed in a3748c4. It will stay like this for current data we have. In the next iteration I will work on the flat option and other references than Person, then will change it.

2020-12-16 10:45 UTC, mpro7 commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +    const replaceReference = (obj: object, ref: string, replacer: any): Dataset => {
Answered [here](https://github.com/dasch-swiss/dsp-js-lib/pull/268#discussion_r544195250).

2020-12-16 10:51 UTC, mpro7 commented
All the `IUrl` interface related questions: until I do not get clear view of how may URL types we could have, I will leave it like that. Of course, if with the next iteration will see benefits of inheritance, will adjust it. For now, there are no benefits from that.

2020-12-16 16:45 UTC, tobiasschweizer reviewed
Could you check this comment on the previous PR: https://github.com/dasch-swiss/dsp-js-lib/pull/258/files/de6cbdbcba4c16707b1b2155a69f6b536883816c#diff-9a682acaad7adb19b18d7479b0f72f44896b792f949a1dc02011f734ac8d861e?

Could you add a DSP task to add unit tests once there will be test data for them?

2020-12-16 16:45 UTC, tobiasschweizer commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        meta.projectsMetadata.push(...datasets);
Couldn't you simply assign `datasets`? The array is empty anyway, so you do not have to combine it.

`meta.projectsMetadata = datasets`

2020-12-16 16:45 UTC, tobiasschweizer commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        let meta = new ProjectsMetadata();
could be made `const`

2020-12-16 16:45 UTC, tobiasschweizer commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        for (const key in tempObj) {
So this will then relate to the TODO / DSP task mentioned above?

2020-12-16 16:45 UTC, tobiasschweizer commented on src/index.ts
> +export { IUrl } from "./models/v2/custom-converters/base-url-converter";
Ok, understood.

2020-12-16 16:45 UTC, tobiasschweizer commented on src/models/v2/custom-converters/advanced-url-object-converter.ts
> +                [Constants.SchemaPropID]: val.name
So the benefit that you get from the interface is that property names cannot be misspelled?

2020-12-16 16:45 UTC, tobiasschweizer commented on src/models/v2/custom-converters/advanced-url-object-converter.ts
> +    deserialize(val: any): IUrl {
I remember from yesterday's conversation that it does not make sense to make different interfaces connected via inheritance. Correct? Or could this be refactored some day?

2020-12-16 16:45 UTC, tobiasschweizer commented on src/models/v2/project-metadata/dataset-definition.ts
>  import { DateConverter } from "../custom-converters/date-converter";
I missed that in the first review: could you make the class names consistent with the file names?

2020-12-16 16:45 UTC, tobiasschweizer commented on src/models/v2/project-metadata/dataset-definition.ts
>  import { DateConverter } from "../custom-converters/date-converter";
just rename he file to `dataset.ts`. The same for the other models.

2020-12-16 16:45 UTC, tobiasschweizer commented on src/models/v2/project-metadata/base-project-metadata.ts
> +        this.type = type;
Yes, I will dump the contents of my brain and make a tar file next time.

2020-12-16 16:45 UTC, tobiasschweizer commented on src/models/v2/project-metadata/base-project-metadata.ts
> +export class BaseProjectMetadata {
Is this ever instantiated directly? If not, you can make it abstract and categorize it as internal.

2020-12-16 16:45 UTC, tobiasschweizer commented on src/models/v2/project-metadata/place-definition.ts
> +    place: IUrl = {} as IUrl;
Maybe you should rename the `PlayConverter` then. `PlayConverter` seems to deal with `IUrl`, right?

2020-12-16 16:51 UTC, tobiasschweizer commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        meta.projectsMetadata.push(datasetObj as Dataset);
>  But currently on test-framework I place them outside.

What happens if the user works with the data structure provided by `ProjectMetadataEndpointV2.getProjectMetadata`, just manipulates some members and then passes this to `ProjectMetadataEndpointV2.updateProjectMetadata`? Would the persons be nested in `Dataset`?

2020-12-16 16:57 UTC, mpro7 commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        for (const key in tempObj) {
Correct

2020-12-16 16:59 UTC, mpro7 commented on src/models/v2/custom-converters/advanced-url-object-converter.ts
> +                [Constants.SchemaPropID]: val.name
You also think in the other way, you have 4 possibilities of properties to have inside, still better than primitive `object`.

2020-12-16 17:46 UTC, mpro7 commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        meta.projectsMetadata.push(datasetObj as Dataset);
Currently no. I try to keep it consistent. All depends what user will modify. User is able to modify everything which is compatible with the model. And with flat structure, this will no matter. At least from my understanding how this works.

2020-12-16 17:48 UTC, mpro7 commented on src/models/v2/custom-converters/advanced-url-object-converter.ts
> +    deserialize(val: any): IUrl {
Correct and as stated [here](https://github.com/dasch-swiss/dsp-js-lib/pull/268#issuecomment-746089532).

2020-12-16 17:54 UTC, mpro7 commented on src/models/v2/project-metadata/place-definition.ts
> +    place: IUrl = {} as IUrl;
Why? It serialises to Place type object and deserialises to URL type of object. This could be probably later on distinguish.

2020-12-16 18:02 UTC, mpro7 commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        // TODO: consider other obejcts placed outside the Dataset object(s) and/or simplify/adjust it to known possibilities
I'll try to ask for it.

2020-12-16 18:09 UTC, mpro7 commented on src/models/v2/project-metadata/base-project-metadata.ts
> +export class BaseProjectMetadata {
That's strange I could let cut my hand I defined it as an abstract class. But this could be also another base class I've created and I would be one hand bandit.

2020-12-17 07:13 UTC, tobiasschweizer approved these changes
Please add DSP tasks for the refactoring of the [conversion method](https://github.com/dasch-swiss/dsp-js-lib/pull/268#discussion_r544416451) for outer objects like persons and [adding unit tests ](https://github.com/dasch-swiss/dsp-js-lib/pull/268#pullrequestreview-553825498)once there is test data.

2020-12-17 07:13 UTC, tobiasschweizer commented on src/models/v2/project-metadata/metadata-conversion-util.ts
> +        meta.projectsMetadata = [...datasets];
`meta.projectsMetadata = datasets;` is sufficient (`meta.projectsMetadata` is empty)

2020-12-17 09:19 UTC, merged