Prepare release 1.0.0
dasch-swiss/dsp-js-lib pull request #273
Opened 2020-12-14 09:52 UTC by kilchenmann

To run [release-please-action](https://github.com/marketplace/actions/release-please-action) the correct way, we have to do real release first. Otherwise the mentioned action script will not work properly with all the release candidates between latest version and the new one.

2020-12-14 10:13 UTC, kilchenmann commented
When this PR is merged, we can create a new release (v1.0.0)

2020-12-14 10:17 UTC, tobiasschweizer commented on package.json
> +  "version": "1.0.0",
So this won't be done dynamically anymore?

2020-12-14 10:17 UTC, tobiasschweizer commented on CHANGELOG.md
> +
Will the changelog be under version control again?

2020-12-14 10:24 UTC, kilchenmann commented on CHANGELOG.md
> +
Yes, it will be back under version control. Automatically updated by [Release Please Action](https://github.com/marketplace/actions/release-please-action#how-release-please-works)

2020-12-14 10:24 UTC, kilchenmann commented on package.json
> +  "version": "1.0.0",
It would be dynamically updated by [Release Please Action](https://github.com/marketplace/actions/release-please-action#how-release-please-works)

2020-12-14 10:27 UTC, tobiasschweizer commented on CHANGELOG.md
> +
but we couldn't add to it manually, could we?

2020-12-14 10:28 UTC, tobiasschweizer commented on package.json
> +  "version": "1.0.0",
ok, so no placeholder needed then?

2020-12-14 10:45 UTC, kilchenmann commented on CHANGELOG.md
> +
You could still update it in the automatically generated release PR before merging it.

2020-12-14 10:45 UTC, kilchenmann commented on package.json
> +  "version": "1.0.0",
No, not needed anymore

2020-12-14 10:45 UTC, tobiasschweizer commented on package.json
> +  "version": "1.0.0",
cool

2020-12-14 10:47 UTC, tobiasschweizer commented on CHANGELOG.md
> +
sorry, but now I am not sure if I understand correctly:

Wouldn't manual changes simply be overwritten?

2020-12-14 12:12 UTC, tobiasschweizer approved these changes
I think the source of my confusion is that #271 was already merged (changing the workflow) and this PR is about the release PR.

So I think my questions would have applied to #271, not this PR.

2020-12-14 12:13 UTC, tobiasschweizer requested changes
just a second, I spotted something weird

2020-12-14 12:13 UTC, tobiasschweizer commented on CHANGELOG.md
> +- [#214](https://github.com/dasch-swiss/dsp-ui-lib/pull/214) DSP-759 Check if a Given Date Can Be Edited / Rename ValueTypeService to ValueService
this comes from dsp-ui, no ?

2020-12-14 14:31 UTC, kilchenmann commented on CHANGELOG.md
> +- [#214](https://github.com/dasch-swiss/dsp-ui-lib/pull/214) DSP-759 Check if a Given Date Can Be Edited / Rename ValueTypeService to ValueService
Oops yes, you are right. My mistake. That's what happens when you quickly adjust something manully. Fix in d132ea2

2020-12-14 14:37 UTC, kilchenmann commented
> I think the source of my confusion is that #271 was already merged (changing the workflow) and this PR is about the release PR.
> 
> So I think my questions would have applied to #271, not this PR.

I see and understand the confusion. Yes I already merged PR #271 with the new workflow. The new step in actions script created PR #272, which is fact not complete, because we didn't followed yet all the needed commit message rules like `feat!` for a feature which represent a breaking change. This is why I created this release preparation manually. In the future we will use the automatic generated PR from "Release Please action".

2020-12-15 05:28 UTC, kilchenmann commented on CHANGELOG.md
> +
Just do it before merging. Otherwise it will be updated by another merged PR.

2020-12-15 06:55 UTC, tobiasschweizer approved these changes

2020-12-17 06:05 UTC, merged