DSP-1180 - Support Edit List Feature Toggle Endpoints
dasch-swiss/dsp-js-lib pull request #281
Opened 2020-12-18 11:31 UTC by mdelez

resolves DSP-1180

2020-12-18 11:32 UTC, mdelez commented
tests are failing, but exactly sure why but I want to test this in DSP-APP via yalc

2021-01-04 11:58 UTC, mdelez commented
@tobiasschweizer I added a new method to `lists-endpoint-admin` called `updateChildNode` which uses the feature toggle

2021-01-05 10:52 UTC, mdelez commented
@tobiasschweizer
New methods: `updateChildNode`

New methods replacing old methods:
`getListNodeInfoV2` replacing `getListNodeInfo`
`createListV2` replacing `createList`
`getListV2` replacing `getList`

suggestions for better method names are encouraged

2021-01-06 08:45 UTC, tobiasschweizer requested changes
Please see my comments.

2021-01-06 08:45 UTC, tobiasschweizer commented on src/api/admin/lists/lists-endpoint.spec.ts
> +            // test data for this test has been created manually!
Why did you have to generate the test data manually? Is there only test data for updating the node's name?

2021-01-06 08:45 UTC, tobiasschweizer commented on src/api/admin/lists/lists-endpoint-admin.ts
> +
Since `name`, `labels`, and `comments` are all optional properties, would it make sense to check that at least one property is defined?

2021-01-06 08:45 UTC, tobiasschweizer commented on src/api/admin/lists/lists-endpoint-admin.ts
> +    getListNodeInfoV2(listItemIri: string): Observable<ApiResponseData<ListNodeInfoResponse> | ApiResponseError> {
These methods should not be called v2 because this will lead to confusion. There is a part of DSP-API that is called v2, but this PR affects the admin part.

Also once the old methods are removed, the name of the new methods should not be changed.

2021-01-06 08:45 UTC, tobiasschweizer commented on src/api/admin/lists/lists-endpoint-admin.ts
> +    getListNodeInfoV2(listItemIri: string): Observable<ApiResponseData<ListNodeInfoResponse> | ApiResponseError> {
What about just changing the implementation of the old methods (instead of the call through to the new method)?

So `createList`, `getList`, and `getListNodeInfo` would get a new implementation, and there would be no need to add any new methods.

2021-01-06 08:45 UTC, tobiasschweizer commented on test-framework/src/app/app.component.html
> +            <button class="create-list-v1" (click)="createListV1()">Create a list with the old route</button> <br /><br />
Could you add those to the e2e specs?

2021-01-06 08:45 UTC, tobiasschweizer commented on test-framework/src/app/app.component.html
> +            <button class="create-list-v1" (click)="createListV1()">Create a list with the old route</button> <br /><br />
Maybe there is no need for having a v1 and v2 version, sen my comment above. Then this will even get easier.

2021-01-06 09:01 UTC, mdelez commented on src/api/admin/lists/lists-endpoint.spec.ts
> +            // test data for this test has been created manually!
Currently, yes

2021-01-06 09:07 UTC, mdelez commented on src/api/admin/lists/lists-endpoint-admin.ts
> +
Yeah that would make sense. What kind of error should I throw?

2021-01-06 09:09 UTC, tobiasschweizer commented on src/api/admin/lists/lists-endpoint-admin.ts
> +
maybe something like in `PermissionsEndpointAdmin.createDefaultObjectAccessPermission` would be good.

2021-01-06 09:25 UTC, mdelez commented on src/api/admin/lists/lists-endpoint-admin.ts
> +    getListNodeInfoV2(listItemIri: string): Observable<ApiResponseData<ListNodeInfoResponse> | ApiResponseError> {
done in f162865

2021-01-06 10:15 UTC, mdelez commented on src/api/admin/lists/lists-endpoint-admin.ts
> +
done in d0000e8

2021-01-06 11:22 UTC, mdelez commented on test-framework/src/app/app.component.html
> +            <button class="create-list-v1" (click)="createListV1()">Create a list with the old route</button> <br /><br />
done in 11a7aae

2021-01-06 13:14 UTC, tobiasschweizer reviewed
I was wondering wether the implementation of `updateChildName`, `updateChildLabels`, `updateChildComments` could internally call `updateChildNode`.

2021-01-06 13:14 UTC, tobiasschweizer commented on src/api/admin/lists/lists-endpoint.spec.ts
>                      done();
Could you add one assertion here?

2021-01-06 13:14 UTC, tobiasschweizer commented on test-framework/e2e/src/app.e2e-spec.ts
> +  it('should update the labels and comments of a list child node', () => {
Great!

2021-01-06 13:14 UTC, tobiasschweizer commented on test-framework/src/app/app.component.ts
> +                this.listChildName = res.body.nodeinfo.name;
good catch

2021-01-06 13:24 UTC, mdelez commented on test-framework/src/app/app.component.ts
> +                this.listChildName = res.body.nodeinfo.name;
I knew it looked weird :)

2021-01-06 15:50 UTC, mdelez commented on src/api/admin/lists/lists-endpoint.spec.ts
>                      done();
assertions for this and the other comments done in dde6a52

2021-01-06 16:48 UTC, tobiasschweizer approved these changes
Great, thanks!

2021-01-07 08:20 UTC, merged