feat(metadata): adjust all x-n properties and converters (DSP-1222)
dasch-swiss/dsp-js-lib pull request #301
Opened 2021-01-26 10:10 UTC by mpro7

resolves DSP-1222
All properties which have cardinality `x-n` were adjusted and can be either single element or array of elements.

2021-01-28 09:24 UTC, tobiasschweizer requested changes
Please find some cursory comments that apply to various custom converters. I also commented on specific converters but I think these comments also apply to other custom converters.

## Consistent Use of Arrays

My suggestion is to always use arrays in the classes, and then in the custom converter, you just deal with the JSON-LD representation which could be an array or a single object (both on reading and writing).

Example: 

```ts
@JsonObject("Attribution")
export class Attribution extends BaseProjectMetadata {

@JsonProperty(Constants.DspHasRole, UnionStringArrayOfStringsConverter)
role: string[] | string = [];
```

Couldn't role (or roles) always be an array (`role: string[]`)? When reading from JSON-LD just always return an array, and when writing, turn an array with just one element into an object (see for example: https://github.com/dasch-swiss/dsp-js-lib/blob/main/src/models/v2/custom-converters/string-literal-to-string-literal-array-converter.ts).

I think this will make it easier to use the metadata endpoint's classes since the client always deals with the same structure.


##  Tuple vs. Array Annotation

I noticed that you use [tuple](https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple) annotations. Could you use array annotations instead? I think the idea of tuples is that you know the number of elements which is not the case here I think.

This could be helpful: https://www.educative.io/edpresso/arrays-vs-tuples-in-typescript

2021-01-28 09:24 UTC, tobiasschweizer commented on src/models/v2/custom-converters/union-advanced-url-object-converter.ts
> +export class UnionAdvancedUrlObjectConverter implements JsonCustomConvert<IUrl | string | [IUrl | string]> {
same comment about tuples

2021-01-28 09:24 UTC, tobiasschweizer commented on src/models/v2/custom-converters/union-element-array-of-elements-converter.ts
> +    serialize(el: any): any {
couldn't annotate `el: any` as a specific type (either single element or array)?

2021-01-28 09:24 UTC, tobiasschweizer commented on src/models/v2/custom-converters/union-element-array-of-elements-converter.ts
> +export class UnionElementArrayOfElementsConverter implements JsonCustomConvert<any> {
couldn't you use a more specific type than `any`?

2021-01-28 09:24 UTC, tobiasschweizer commented on src/models/v2/custom-converters/union-metadata-converter.ts
> +export class UnionMetadataConverter implements JsonCustomConvert<[Dataset | Person]> {
Would this also work `(Dataset | Person)[]`?

2021-01-28 09:24 UTC, tobiasschweizer commented on src/models/v2/project-metadata/attribution.ts
> +    role: string[] | string = [];
could this always be an array? And then in the custom converter, you just deal with the JSON-LD representation which could be an array or a single object (both on reading and writing)?

2021-01-28 10:57 UTC, mpro7 commented on src/models/v2/custom-converters/base-url-converter.ts
> +            const newObj = [] as any[];
In multiple types arrays there is no other options to distinguish elements only with `son2typescript` library.

2021-01-28 11:01 UTC, mpro7 commented on src/models/v2/custom-converters/base-url-converter.ts
> +    deserialize(val: any): IUrl | IUrl[] | string | string[] {
This is actually wrong, the type annonation should be `IUrl | string | (IUrl | string)[]` and as mentioned above, in multiple types array it isn't possible to use that approach.

2021-01-28 11:04 UTC, mpro7 commented on src/models/v2/project-metadata/attribution.ts
> +    role: string[] | string = [];
Good point, thanks for that. I'll  consider to change it in all possible properties, however this will require a lot of changes with the converters, so might end up moving this to another task.

2021-01-29 07:42 UTC, mpro7 commented on src/models/v2/custom-converters/base-url-converter.ts
> +    serialize(el: IUrl): object | object[] {
Fixed in 2373bf0.

2021-01-29 07:43 UTC, mpro7 commented on src/models/v2/custom-converters/base-url-converter.ts
> +            const newObj = [] as any[];
It could probably be, but as in `json2typescript` lib and in other converters we use any for JSON-LD, so let's keep it consistent. Map is not working here well.

2021-01-29 07:44 UTC, mpro7 commented on src/models/v2/custom-converters/union-advanced-url-object-converter.ts
> +    serialize(el: IUrl | string | [IUrl | string]): any {
Fixed in 2373bf0.

2021-01-29 07:44 UTC, mpro7 commented on src/models/v2/custom-converters/union-advanced-url-object-converter.ts
> +    deserialize(el: any): IUrl | string | [IUrl | string] {
Fixed in 2373bf0.

2021-01-29 07:44 UTC, mpro7 commented on src/models/v2/custom-converters/union-advanced-url-object-converter.ts
> +export class UnionAdvancedUrlObjectConverter implements JsonCustomConvert<IUrl | string | [IUrl | string]> {
Fixed in 2373bf0.

2021-01-29 07:45 UTC, mpro7 commented on src/models/v2/custom-converters/union-element-array-of-elements-converter.ts
> +    serialize(el: any): any {
Fixed in 2373bf0.

2021-01-29 07:45 UTC, mpro7 commented on src/models/v2/custom-converters/union-element-array-of-elements-converter.ts
> +export class UnionElementArrayOfElementsConverter implements JsonCustomConvert<any> {
Fixed in 2373bf0.

2021-01-29 07:45 UTC, mpro7 commented on src/models/v2/custom-converters/union-metadata-converter.ts
> +export class UnionMetadataConverter implements JsonCustomConvert<[Dataset | Person]> {
Fixed in 2373bf0.

2021-01-29 07:56 UTC, mpro7 commented on src/models/v2/custom-converters/base-url-converter.ts
> +    serializeElement(el: IUrl): object {
In this case `protected` but good point, changed access modifiers in d362a3e.

2021-01-29 10:14 UTC, tobiasschweizer commented on src/models/v2/custom-converters/base-url-converter.ts
> +            const newObj = [] as any[];
Maybe we'll figure out why someday, but this is not a priority now. There must some reason related to type inference.

2021-01-29 10:31 UTC, tobiasschweizer approved these changes
I think it would be good to start adding some unit tests soon. E2E tests can easily break and it is sometimes not so simple to spot why they failed exactly.

2021-01-29 10:35 UTC, mpro7 commented
> I think it would be good to start adding some unit tests soon. E2E tests can easily break and it is sometimes not so simple to spot why they failed exactly.

Thanks for review. Yeah, but how w/o test data?

2021-01-29 10:36 UTC, merged

2021-01-29 10:40 UTC, tobiasschweizer commented
> Yeah, but how w/o test data?

valid question